[package]
name = "fast_dss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# lapack = "0.19.0"
anyhow = "~1.0"
# lapack-src = { version="0.9.0", features=["openblas"]}